Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-05, with the labels that each got.

#58 리전 정보 제공 API 구현
  build.gradle
  docs/index.html
  docs/tech-spec/common/region_api.md
  src/docs/asciidoc/api/alcohols/region.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/BottleNoteApplication.java
  src/main/java/app/bottlenote/alcohols/controller/RegionController.java
  src/main/java/app/bottlenote/alcohols/domain/Region.java
  src/main/java/app/bottlenote/alcohols/dto/response/RegionsResponse.java
  src/main/java/app/bottlenote/alcohols/repository/RegionQueryRepository.java
  src/main/java/app/bottlenote/alcohols/service/RegionService.java
  src/main/java/app/bottlenote/global/cache/local/LocalCacheConfig.java
  src/main/java/app/bottlenote/global/cache/local/LocalCacheType.java
  src/test/java/app/bottlenote/alcohols/controller/RegionControllerTest.java
  src/test/java/app/bottlenote/alcohols/service/RegionServiceTest.java
  src/test/java/app/bottlenote/docs/alcohols/RestRegionControllerTest.java
Labels: documentation, feat, test

#59 hotfix 🔥 category 추가
  docs/index.html
  src/main/java/app/bottlenote/alcohols/dto/response/Populars.java
  src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
  src/test/java/app/bottlenote/docs/alcohols/RestPopularControllerTest.java
Labels: bug, documentation

#63 Pr/62 RatingPoint Value Object
  database/mysql/init/01-init-table.sql
  src/main/java/app/bottlenote/global/config/WebConfig.java
  src/main/java/app/bottlenote/global/service/converter/RatingPointConverter.java
  src/main/java/app/bottlenote/rating/controller/RatingController.java
  src/main/java/app/bottlenote/rating/domain/Rating.java
  src/main/java/app/bottlenote/rating/domain/RatingId.java
  src/main/java/app/bottlenote/rating/domain/RatingPoint.java
  src/main/java/app/bottlenote/rating/exception/RatingException.java
  src/main/java/app/bottlenote/rating/exception/RatingExceptionCode.java
  src/main/java/app/bottlenote/rating/repository/RatingRepository.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/app/bottlenote/global/service/converter/RatingPointConverterTest.java
  src/test/java/app/bottlenote/rating/domain/RatingPointTest.java
  src/test/java/app/bottlenote/support/report/controller/ReportCommandControllerTest.java
Labels: feat

#48 OAuth2 기능 구현
  docs/tech-spec/user/user-tech-spec.md
  src/main/java/app/bottlenote/common/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/common/jwt/JwtTokenProvider.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/security/SecurityUtil.java
  src/main/java/app/bottlenote/global/security/SocialLoginAuthenticationProvider.java
  src/main/java/app/bottlenote/user/controller/OauthController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/dto/request/OauthRequest.java
  src/main/java/app/bottlenote/user/dto/request/TokenRequest.java
  src/main/java/app/bottlenote/user/dto/response/OauthResponse.java
  src/main/java/app/bottlenote/user/exception/UserExceptionCode.java
  src/main/java/app/bottlenote/user/repository/OauthRepository.java
  src/main/java/app/bottlenote/user/service/NicknameGenerator.java
  src/main/java/app/bottlenote/user/service/OauthService.java
  src/main/java/app/bottlenote/user/service/RandomLetterNicknameGenerator.java
  src/main/resources/application-local.yml
Labels: feat, test

#70 로그인 기능 테스트 코드 및 RestDocs
  build.gradle
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/security/SecurityUtil.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationManager.java
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenProvider.java
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenValidator.java
  src/main/java/app/bottlenote/user/domain/constant/GenderType.java
  src/main/java/app/bottlenote/user/dto/request/OauthRequest.java
  src/main/java/app/bottlenote/user/service/OauthService.java
  src/test/java/app/bottlenote/docs/user/OauthControllerDocsTest.java
  src/test/java/app/bottlenote/user/controller/OauthControllerTest.java
  src/test/java/app/bottlenote/user/service/OauthServiceTest.java
Labels: bug, documentation, test

#72 hotfix🔥 : restdocs 테스트 경로 수정
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/test/java/app/bottlenote/docs/user/OauthControllerDocsTest.java
Labels: bug

#78 리뷰 조회 기능 구현
  database/mysql/init/01-init-table.sql
  database/mysql/init/02-init-data.sql
  docs/tech-spec/review/review-read-techspec.md
  src/docs/asciidoc/api/review/review-read.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/like/domain/Likes.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/review/domain/constant/ReviewSortType.java
  src/main/java/app/bottlenote/review/dto/request/PageableRequest.java
  src/main/java/app/bottlenote/review/dto/response/ReviewDetail.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
  src/main/java/app/bottlenote/review/repository/CustomReviewRepository.java
  src/main/java/app/bottlenote/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/repository/ReviewRepository.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
Labels: documentation, feat, test, Deploy

#79 Pr/53유저닉네임 변경 기능구현
  docs/index.html
  docs/tech-spec/user/user_nickname_change.md
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-nickname-change.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/support/report/service/UserReportService.java
  src/main/java/app/bottlenote/user/controller/UserCommandController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/dto/request/NicknameChangeRequest.java
  src/main/java/app/bottlenote/user/dto/response/NicknameChangeResponse.java
  src/main/java/app/bottlenote/user/exception/UserExceptionCode.java
  src/main/java/app/bottlenote/user/repository/UserCommandRepository.java
  src/main/java/app/bottlenote/user/repository/UserRepository.java
  src/main/java/app/bottlenote/user/service/UserCommandService.java
  src/test/java/app/bottlenote/alcohols/repository/CustomAlcoholQueryRepositoryImplTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserChangeContollerTest.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/support/report/service/UserReportServiceTest.java
  src/test/java/app/bottlenote/user/controller/UserNicknameChangeControllerTest.java
  src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
Labels: feat

#82 Pr/61 주간 인기 위스키 조회 수정
  docs/index.html
  src/main/java/app/bottlenote/alcohols/controller/PopularController.java
  src/main/java/app/bottlenote/alcohols/dto/response/Populars.java
  src/main/java/app/bottlenote/alcohols/repository/CustomPopularQueryRepository.java
  src/main/java/app/bottlenote/alcohols/repository/CustomPopularQueryRepositoryImpl.java
  src/main/java/app/bottlenote/alcohols/repository/PopularQueryRepository.java
  src/main/java/app/bottlenote/alcohols/service/PopularService.java
  src/test/java/app/bottlenote/alcohols/repository/CustomPopularQueryRepositoryImplTest.java
  src/test/java/app/bottlenote/docs/alcohols/RestPopularControllerTest.java
Labels: documentation, feat, test

#92 Pr/88 5월3주 수정 사항
  docs/index.html
  src/docs/asciidoc/api/alcohols/detail.adoc
  src/docs/asciidoc/api/alcohols/picks.adoc
  src/docs/asciidoc/api/alcohols/popular.adoc
  src/docs/asciidoc/api/alcohols/region.adoc
  src/docs/asciidoc/api/alcohols/search.adoc
  src/docs/asciidoc/api/review/review-read.adoc
  src/docs/asciidoc/api/support/report/user-report.adoc
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-nickname-change.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/dto/response/detail/AlcoholDetailInfo.java
  src/main/java/app/bottlenote/alcohols/dto/response/detail/ReviewsDetailInfo.java
  src/main/java/app/bottlenote/alcohols/repository/CustomAlcoholQueryRepositoryImpl.java
  src/main/java/app/bottlenote/alcohols/service/AlcoholQueryService.java
  src/main/java/app/bottlenote/review/repository/CustomReviewQueryRepositoryImpl.java
  src/main/java/app/bottlenote/review/repository/ReviewQueryRepository.java
  src/main/resources/static/index.html
  src/test/java/app/bottlenote/docs/alcohols/RestAlcoholQueryControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: documentation, test, Deploy

#91 Pr/90 로그인 토큰재발급 수정사항 반영
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenProvider.java
  src/main/java/app/bottlenote/user/controller/OauthController.java
  src/main/java/app/bottlenote/user/dto/request/TokenRequest.java
  src/main/java/app/bottlenote/user/dto/response/OauthResponse.java
  src/main/java/app/bottlenote/user/dto/response/TokenDto.java
  src/main/java/app/bottlenote/user/service/OauthService.java
  src/test/java/app/bottlenote/docs/user/OauthControllerDocsTest.java
  src/test/java/app/bottlenote/user/controller/OauthControllerTest.java
  src/test/java/app/bottlenote/user/service/JwtTokenValidatorTest.java
  src/test/java/app/bottlenote/user/service/OauthServiceTest.java
Labels: documentation, test, Deploy

#97 hotfix : follow 테이블 status init추가 🔥
  database/mysql/init/01-init-table.sql
Labels: feat

#99 🔥 🔥 🔥 hotfix/security-filter-apply
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  http/위스키_조회.http
  http/토큰_발급.http
  src/main/java/app/bottlenote/alcohols/controller/AlcoholQueryController.java
  src/main/java/app/bottlenote/alcohols/controller/PopularController.java
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/security/SecurityContextUtil.java
  src/main/java/app/bottlenote/global/security/SecurityUtil.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenValidator.java
  src/main/java/app/bottlenote/picks/controller/PicksCommandController.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/user/controller/UserCommandController.java
  src/main/java/app/bottlenote/user/dto/request/NicknameChangeRequest.java
  src/test/java/app/bottlenote/BottleNoteApplicationTest.java
  src/test/java/app/bottlenote/alcohols/controller/AlcoholQueryControllerTest.java
  src/test/java/app/bottlenote/docs/alcohols/RestPicksCommandControllerTest.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/docs/user/OauthControllerDocsTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserChangeContollerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
  src/test/java/app/bottlenote/user/controller/OauthControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserNicknameChangeControllerTest.java
  src/test/java/app/bottlenote/user/service/JwtTokenValidatorTest.java
  src/test/java/app/bottlenote/user/service/OauthServiceTest.java
  src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
Labels: 문서, 기능, 테스트

#94 feat: image upload url
  build.gradle
  docker-compose.yml
  docs/index.html
  docs/tech-spec/common/image-upload.md
  docs/tech-spec/follow/follow-tec-spec.md
  http/http-client.env.json
  http/위스키_조회.http
  http/이미지_업로드.http
  http/토큰_발급.http
  src/docs/asciidoc/api/alcohols/search.adoc
  src/docs/asciidoc/api/file/image/upload/presign-url.adoc
  src/docs/asciidoc/api/follow/follow-update.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/dto/response/detail/ReviewsDetailInfo.java
  src/main/java/app/bottlenote/common/controller/CommonController.java
  src/main/java/app/bottlenote/common/dto/request/RestdocsRequest.java
  src/main/java/app/bottlenote/common/dto/response/RestdocsResponse.java
  src/main/java/app/bottlenote/common/file/PreSignUrlProvider.java
  src/main/java/app/bottlenote/common/file/S3EventListener.java
  src/main/java/app/bottlenote/common/file/exception/FileException.java
  src/main/java/app/bottlenote/common/file/exception/FileExceptionCode.java
  src/main/java/app/bottlenote/common/file/upload/ImageUploadController.java
  src/main/java/app/bottlenote/common/file/upload/ImageUploadService.java
  src/main/java/app/bottlenote/common/file/upload/S3RequestEvent.java
  src/main/java/app/bottlenote/common/file/upload/dto/request/ImageUploadRequest.java
  src/main/java/app/bottlenote/common/file/upload/dto/response/ImageUploadInfo.java
  src/main/java/app/bottlenote/common/file/upload/dto/response/ImageUploadResponse.java
  src/main/java/app/bottlenote/common/service/CommonService.java
  src/main/java/app/bottlenote/follow/controller/FollowCommandController.java
  src/main/java/app/bottlenote/follow/domain/Follow.java
  src/main/java/app/bottlenote/follow/domain/constant/FollowStatus.java
  src/main/java/app/bottlenote/follow/dto/FollowUpdateRequest.java
  src/main/java/app/bottlenote/follow/dto/FollowUpdateResponse.java
  src/main/java/app/bottlenote/follow/exception/FollowException.java
  src/main/java/app/bottlenote/follow/exception/FollowExceptionCode.java
  src/main/java/app/bottlenote/follow/repository/FollowCommandRepository.java
  src/main/java/app/bottlenote/follow/service/FollowCommandService.java
  src/main/java/app/bottlenote/global/config/AsyncConfig.java
  src/main/java/app/bottlenote/global/config/AwsS3Config.java
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/user/dto/request/NicknameChangeRequest.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/app/bottlenote/common/file/upload/ImageUploadControllerTest.java
  src/test/java/app/bottlenote/common/file/upload/ImageUploadServiceTest.java
  src/test/java/app/bottlenote/common/file/upload/fakes/AbstractFakeAmazonS3.java
  src/test/java/app/bottlenote/common/file/upload/fakes/FakeAmazonS3.java
  src/test/java/app/bottlenote/common/file/upload/fakes/FakeEventPublisher.java
  src/test/java/app/bottlenote/common/file/upload/fakes/FakeImageUploadServiceTest.java
  src/test/java/app/bottlenote/docs/common/RestCommonControllerTest.java
  src/test/java/app/bottlenote/docs/follow/RestDocsFollowControllerTest.java
  src/test/java/app/bottlenote/docs/upload/RestImageUploadControllerTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserChangeContollerTest.java
  src/test/java/app/bottlenote/user/controller/UserNicknameChangeControllerTest.java
Labels: 기능, 테스트, 배포

#103 pr/101 팔로우 팔로잉 테스트코드 구현
  docs/index.html
  src/test/java/app/bottlenote/follow/controller/FollowUpdateControllerTest.java
  src/test/java/app/bottlenote/follow/service/FollowCommandServiceTest.java
Labels: 테스트
