Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-07, with the labels that each got.

#150 test: 리뷰 댓글 작성기능에 대한 테스트가 필요하다
  build.gradle
  docs/index.html
  http/별점_목록_조회.http
  src/docs/asciidoc/api/review/reply/review-reply-registry.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/review/domain/ReviewReply.java
  src/main/java/app/bottlenote/review/domain/ReviewRepository.java
  src/main/java/app/bottlenote/review/dto/request/ReviewReplyRegisterRequest.java
  src/main/java/app/bottlenote/review/dto/response/ReviewReplyResponse.java
  src/main/java/app/bottlenote/review/repository/JpaReviewRepository.java
  src/main/java/app/bottlenote/review/service/ReviewReplyService.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/test/java/app/bottlenote/docs/review/RestReviewReplyControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewReplyControllerTest.java
  src/test/java/app/bottlenote/review/fixture/FakeProfanityClient.java
  src/test/java/app/bottlenote/review/fixture/FakeUserDomainSupport.java
  src/test/java/app/bottlenote/review/fixture/InmemoryReviewRepository.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
  src/test/java/app/bottlenote/review/repository/CustomJpaReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/ReviewReplyServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
Labels: 리펙토링, 테스트

#159 Hotfix/이미지업로드 경우에 잘못된 prefix를 수정한다
  docs/index.html
  docs/tech-spec/review/리뷰댓글-목록-조회.md
  http/이미지 업로드 경로를 요청할 수 있다.http
  http/이미지_업로드.http
  src/docs/asciidoc/api/file/image/upload/presign-url.adoc
  src/main/java/app/bottlenote/common/file/PreSignUrlProvider.java
  src/main/java/app/bottlenote/common/file/upload/ImageUploadService.java
  src/test/java/app/bottlenote/common/file/upload/CoreImageUploadServiceTest.java
  src/test/java/app/bottlenote/common/file/upload/ImageUploadControllerTest.java
  src/test/java/app/bottlenote/common/file/upload/ImageUploadServiceTest.java
  src/test/java/app/bottlenote/common/file/upload/fakes/FakeImageUploadServiceTest.java
  src/test/java/app/bottlenote/common/file/upload/fixture/AbstractFakeAmazonS3.java
  src/test/java/app/bottlenote/common/file/upload/fixture/FakeAmazonS3.java
  src/test/java/app/bottlenote/common/file/upload/fixture/FakeImageEventPublisher.java
Labels: 문서, 테스트, 배포

#163 깃허브 페이지 배포 방식을 레거시 -> github action으로 수정
  .github/workflows/ github-pages.yml
Labels: 문서, 리펙토링, 배포

#162 chore : image_key, image_path 컬럼삭제, init-sql도 수정
  .github/init-sql-backup/init-user.sql
Labels: 데이터

#165 hotfix : 누락된 docs 수정
  src/docs/asciidoc/index.adoc
Labels: 문서

#167 feat: 알코올에 대한 유저의 별점을 조회하는 api 가 필요하다
  docs/index.html
  http/공통/이미지 업로드 경로를 요청할 수 있다.http
  http/리뷰/리뷰_조회.http
  http/리뷰/리뷰의 댓글을 달수 있다.http
  http/별점/별점_등록_요청.http
  http/별점/별점_목록_조회.http
  http/별점/유저_별점_조회.http
  http/사용자/닉네임_변경.http
  http/사용자/유저_레포트.http
  http/사용자/토큰_발급.http
  http/사용자/팔로우_요청.http
  http/사용자/팔로우_조회.http
  http/사용자/팔로워_조회.http
  http/사용자/프로필이미지_변경.http
  http/위스키/위스키_조회.http
  http/위스키/위스키_주간인기_조회.http
  http/위스키/위스키_지역_조회.http
  http/위스키/위스키_찜하기.http
  http/위스키/위스키_카테고리_조회.http
  src/docs/asciidoc/api/rating/user-rating.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/rating/controller/RatingController.java
  src/main/java/app/bottlenote/rating/domain/RatingRepository.java
  src/main/java/app/bottlenote/rating/dto/response/UserRatingResponse.java
  src/main/java/app/bottlenote/rating/exception/RatingExceptionCode.java
  src/main/java/app/bottlenote/rating/repository/JpaRatingRepository.java
  src/main/java/app/bottlenote/rating/service/RatingQueryService.java
  src/main/java/app/bottlenote/user/service/domain/DefaultUserDomainSupport.java
  src/test/java/app/bottlenote/docs/rating/RestRatingControllerTest.java
  src/test/java/app/bottlenote/rating/fixture/InMemoryRatingRepository.java
Labels: 기능

#173 refactor : 리뷰상세조회 response에 수정이 필요하다
  src/main/java/app/bottlenote/review/domain/Review.java
  src/main/java/app/bottlenote/review/domain/ReviewRepository.java
  src/main/java/app/bottlenote/review/dto/response/ReviewDetailResponse.java
  src/main/java/app/bottlenote/review/dto/response/ReviewListResponse.java
  src/main/java/app/bottlenote/review/dto/response/ReviewReplyResponse.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResultResponse.java
  src/main/java/app/bottlenote/review/dto/response/constant/ReviewReplyResultMessage.java
  src/main/java/app/bottlenote/review/dto/response/constant/ReviewResultMessage.java
  src/main/java/app/bottlenote/review/repository/ReviewQuerySupporter.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepository.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/service/ReviewReplyService.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/fixture/InMemoryReviewRepository.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
  src/test/java/app/bottlenote/review/repository/CustomJpaReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/ReviewReplyServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
Labels: 문서, 리펙토링, 테스트, 배포

#179 fix rating 조회시에도 카테고리 그룹 조회가 추가되어야한다
  docs/index.html
  http/별점/별점_목록_조회.http
  src/main/java/app/bottlenote/rating/controller/RatingController.java
  src/main/java/app/bottlenote/rating/dto/dsl/RatingListFetchCriteria.java
  src/main/java/app/bottlenote/rating/dto/request/RatingListFetchRequest.java
  src/main/java/app/bottlenote/rating/repository/RatingQuerySupporter.java
  src/test/java/app/bottlenote/docs/rating/RestRatingControllerTest.java
  src/test/java/app/bottlenote/rating/fixture/RatingObjectFixture.java
Labels: 리펙토링, 테스트

#189 feat : 데이터 변경시 생성자와 변경자가 기록되지 않는 문제를 해결한다.
  src/main/java/app/bottlenote/global/config/jpa/AuditorAwareImpl.java
  src/main/java/app/bottlenote/global/config/jpa/JpaConfig.java
  src/main/java/app/bottlenote/global/config/jpa/QueryDslConfig.java
  src/test/java/app/bottlenote/global/config/JpaAuditingIntegrationTest.java
  src/test/java/app/bottlenote/global/config/JpaAuditingTest.java
  src/test/java/app/bottlenote/global/customMockUser/CustomUserDetails.java
  src/test/java/app/bottlenote/global/customMockUser/WithMockCustomUser.java
  src/test/java/app/bottlenote/global/customMockUser/WithMockCustomUserSecurityContextFactory.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
Labels: 버그, 리펙토링, 테스트

#192 hotfix : 리뷰 조회 시 삭제 된 리뷰가 조회되는 현상을 해결한다
  database/mysql/init/01-init-table.sql
  database/mysql/init/02-init-data.sql
  src/main/java/app/bottlenote/review/dto/response/ReviewDetailResponse.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
  src/test/resources/init-script/schema.sql
Labels: 버그, 배포

#199 hotfix : 리뷰 수정시 발생하는 문제들을 해결한다
  src/main/java/app/bottlenote/review/domain/constant/SizeType.java
  src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
  src/main/java/app/bottlenote/review/dto/request/ReviewModifyRequest.java
  src/main/java/app/bottlenote/review/dto/vo/ReviewModifyVO.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewQueryRepositoryImpl.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/service/ReviewImageSupport.java
  src/main/java/app/bottlenote/review/service/ReviewTastingTagSupport.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
  src/test/java/app/bottlenote/review/integration/ReviewIntegerationTest.java
Labels: 버그, 리펙토링

#208 fix: rename a strange file name
  .github/workflows/github-pages.yml
Labels: 버그, 배포

#207 feat : 회원 탈퇴 기능을 구현한다
  database/mysql/init/01-init-table.sql
  database/mysql/init/02-init-data.sql
  src/docs/asciidoc/api/user/user-withdraw.adoc
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenProvider.java
  src/main/java/app/bottlenote/user/controller/UserCommandController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/domain/constant/UserStatus.java
  src/main/java/app/bottlenote/user/dto/response/WithdrawUserResultResponse.java
  src/main/java/app/bottlenote/user/dto/response/constant/WithdrawUserResultMessage.java
  src/main/java/app/bottlenote/user/service/UserCommandService.java
  src/main/java/app/bottlenote/user/service/domain/DefaultUserDomainSupport.java
  src/test/java/app/bottlenote/IntegrationTestSupport.java
  src/test/java/app/bottlenote/docs/user/RestOauthControllerTest.java
  src/test/java/app/bottlenote/docs/user/RestUserCommandControllerTest.java
  src/test/java/app/bottlenote/review/integration/ReviewIntegrationTest.java
  src/test/java/app/bottlenote/user/controller/UserCommandControllerTest.java
  src/test/java/app/bottlenote/user/fixture/UserObjectFixture.java
  src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
  src/test/java/app/bottlenote/user/integration/UserQueryIntegrationTest.java
  src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
  src/test/resources/init-script/init-user-mypage-query.sql
  src/test/resources/init-script/init-user.sql
  src/test/resources/init-script/schema.sql
Labels: 문서, 기능, 테스트, 배포
