Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-04, with the labels that each got.

#23 Pr/8 oauth2 user
  build.gradle
  docs/wiki/exception 사용 가이드 요청.md
  src/main/java/app/bottlenote/common/jwt/JwtTokenProvider.java
  src/main/java/app/bottlenote/user/controller/OauthController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/domain/Users.java
  src/main/java/app/bottlenote/user/domain/constant/GenderType.java
  src/main/java/app/bottlenote/user/domain/constant/SocialType.java
  src/main/java/app/bottlenote/user/domain/constant/UserType.java
  src/main/java/app/bottlenote/user/dto/request/OauthRequest.java
  src/main/java/app/bottlenote/user/dto/response/OauthResponse.java
  src/main/java/app/bottlenote/user/repository/OauthRepository.java
  src/main/java/app/bottlenote/user/service/NicknameGenerator.java
  src/main/java/app/bottlenote/user/service/OauthService.java
  src/main/resources/application.yml
Labels: feat

#25 Pr/24
  docs/tech-spec/tech-spec-guide.md
  docs/wiki/exception 사용 가이드 요청.md
  docs/wiki/exception/exception_guide.md
  docs/wiki/exception/img.png
  docs/wiki/jpa/jpa_entity_spec_guide.md
  src/main/java/app/bottlenote/alcohols/domain/Alcohol.java
  src/main/java/app/bottlenote/alcohols/domain/AlcoholsTastingTags.java
  src/main/java/app/bottlenote/alcohols/domain/Country.java
  src/main/java/app/bottlenote/alcohols/domain/Distillery.java
  src/main/java/app/bottlenote/alcohols/domain/TastingTag.java
  src/main/java/app/bottlenote/alcohols/domain/Tier.java
  src/main/java/app/bottlenote/alcohols/domain/constant/AlcoholType.java
  src/main/java/app/bottlenote/common/domain/BaseEntity.java
  src/main/java/app/bottlenote/global/exception/custom/code/ExceptionCode.java
  src/main/java/app/bottlenote/rating/domain/Rating.java
  src/main/java/app/bottlenote/review/domain/Review.java
  src/main/java/app/bottlenote/review/domain/ReviewImage.java
  src/main/java/app/bottlenote/review/domain/ReviewReply.java
  src/main/java/app/bottlenote/review/domain/constant/ImageStatus.java
  src/main/java/app/bottlenote/review/domain/constant/SizeType.java
  src/main/java/app/bottlenote/support/constant/StatusType.java
  src/main/java/app/bottlenote/support/help/domain/Help.java
  src/main/java/app/bottlenote/support/report/domain/ReviewReport.java
  src/main/java/app/bottlenote/support/report/domain/UserReports.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/exception/UserException.java
  src/main/java/app/bottlenote/user/exception/UserExceptionCode.java
  src/main/java/app/bottlenote/user/repository/OauthRepository.java
  src/main/java/app/bottlenote/user/service/OauthService.java
Labels: feat

#26 Pr/20 create docker-compose.yml(mysql + redis)
  Dockerfile
  build.gradle
  database/mysql/config/my.cnf
  database/mysql/init/init-alcohol.sql
  database/mysql/init/init-rating.sql
  database/mysql/init/init-review.sql
  database/mysql/init/init-support.sql
  database/mysql/init/init-tasting-tag.sql
  database/mysql/init/init-user.sql
  docker-compose.yml
  mysql-init/init.sql
  src/main/java/app/bottlenote/common/domain/BaseEntity.java
  src/main/java/app/bottlenote/rating/domain/Rating.java
  src/main/java/app/bottlenote/review/domain/Review.java
  src/main/java/app/bottlenote/review/domain/ReviewImage.java
  src/main/java/app/bottlenote/support/help/domain/Help.java
  src/main/java/app/bottlenote/support/report/domain/ReviewReport.java
  src/main/java/app/bottlenote/support/report/domain/UserReports.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/resources/application.yml
Labels: infra

#33 Isolate local, dev, and prod environments(application.yml)
  .database/redis/data/dump.rdb
  .gitignore
  redis/data/dump.rdb
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: infra, CI/CD

#31 user report api
  build.gradle
  database/mysql/init/init-alcohol.sql
  database/mysql/init/init-rating.sql
  database/mysql/init/init-review.sql
  database/mysql/init/init-support.sql
  database/mysql/init/init-tasting-tag.sql
  database/mysql/init/init-user.sql
  docs/tech-spec/support/user_report.md
  src/main/java/app/bottlenote/global/data/response/GlobalResponse.java
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/exception/util/ExceptionUtil.java
  src/main/java/app/bottlenote/support/report/controller/ReportCommandController.java
  src/main/java/app/bottlenote/support/report/domain/UserReports.java
  src/main/java/app/bottlenote/support/report/domain/constant/UserReportType.java
  src/main/java/app/bottlenote/support/report/dto/request/UserReportRequest.java
  src/main/java/app/bottlenote/support/report/dto/response/UserReportResponse.java
  src/main/java/app/bottlenote/support/report/exception/ReportException.java
  src/main/java/app/bottlenote/support/report/exception/ReportExceptionCode.java
  src/main/java/app/bottlenote/support/report/repository/UserReportRepository.java
  src/main/java/app/bottlenote/support/report/service/UserReportService.java
  src/main/java/app/bottlenote/user/controller/OauthController.java
  src/main/java/app/bottlenote/user/dto/request/OauthRequest.java
  src/main/java/app/bottlenote/user/exception/UserExceptionCode.java
  src/main/java/app/bottlenote/user/repository/UserRepository.java
Labels: documentation, feat, test

#36 Pr/16 restdocs 설정 관련 이슈
  build.gradle
  docs/index.html
  docs/wiki/rest-docs/rest-docs-guide.md
  src/docs/asciidoc/api/overview/overview.adoc
  src/docs/asciidoc/api/restdocs/restdocs-example.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/common/controller/CommonController.java
  src/main/java/app/bottlenote/common/dto/request/RestdocsRequest.java
  src/main/java/app/bottlenote/common/dto/response/RestdocsResponse.java
  src/main/java/app/bottlenote/common/service/CommonService.java
  src/main/java/app/bottlenote/global/service/meta/MetaInfos.java
  src/main/java/app/bottlenote/global/service/meta/MetaService.java
  src/main/resources/static/docs/index.adoc
  src/test/java/app/bottlenote/docs/AbstractRestDocs.java
  src/test/java/app/bottlenote/docs/common/RestCommonControllerTest.java
  src/test/java/app/bottlenote/docs/config/RestDocsConfiguration.java
  src/test/java/app/bottlenote/global/exception/util/ExceptionUtilTest.java
  src/test/java/app/bottlenote/global/service/meta/MetaServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: documentation, test

#40 feat : SecurityConfig - cors 허용 설정
  build.gradle
  database/mysql/init/init-user.sql
  database/redis/data/dump.rdb
  docs/wiki/security/security_cors_guide.md
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
Labels: feat

#39 Pr/38 유저 신고 기능 테스트 코드 작성
  docker-compose.yml
  docs/index.html
  src/docs/asciidoc/api/overview/global-exception.adoc
  src/docs/asciidoc/api/overview/global-response.adoc
  src/docs/asciidoc/api/overview/overview.adoc
  src/docs/asciidoc/api/restdocs/restdocs-example.adoc
  src/docs/asciidoc/api/support/report/user-report.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/common/controller/CommonController.java
  src/main/java/app/bottlenote/global/exception/custom/AbstractCustomException.java
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/exception/util/ExceptionUtil.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/service/meta/MetaInfos.java
  src/main/java/app/bottlenote/support/report/domain/UserReports.java
  src/main/java/app/bottlenote/support/report/exception/ReportExceptionCode.java
  src/main/java/app/bottlenote/support/report/service/UserReportService.java
  src/test/java/app/bottlenote/config/ModuleConfig.java
  src/test/java/app/bottlenote/docs/common/RestCommonControllerTest.java
  src/test/java/app/bottlenote/docs/support/report/RestDocsReportCommandControllerTest.java
  src/test/java/app/bottlenote/global/exception/util/ExceptionUtilTest.java
  src/test/java/app/bottlenote/support/report/controller/ReportCommandControllerTest.java
  src/test/java/app/bottlenote/support/report/service/UserReportServiceTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: documentation, test

#46 fix: init sql and docker compose not used volumes
  database/mysql/init/init-alcohol.sql
  database/mysql/init/init-review.sql
  database/redis/data/dump.rdb
  docker-compose.yml
Labels: data, infra

#52 Pr/49 개발 환경 배포
  .github/workflows/code_quality.yml
  .github/workflows/dev_deploy_workflow.yml
  .gitignore
  Dockerfile
  docker-compose-dev.yml
  docs/index.html
  gradlew
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: CI/CD, Deploy

#55 Pr/51 actuator
  .gitignore
  build.gradle
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
Labels: data, CI/CD
