Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-08, with the labels that each got.

#222 refactor : review 도메인 프론트 요청사항을 반영 (테스트 코드 추가)
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/test/java/app/bottlenote/review/integration/ReviewIntegrationTest.java
  src/test/java/app/bottlenote/user/fixture/UserObjectFixture.java
Labels: 테스트, 배포

#228 refactor: add review reply status to response object
  http/리뷰/리뷰의 댓글을 조회할 수 있다.http
  src/main/java/app/bottlenote/review/dto/response/RootReviewReplyInfo.java
  src/main/java/app/bottlenote/review/dto/response/SubReviewReplyInfo.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewReplyRepositoryImpl.java
Labels: 기능

#226 refactor : 리뷰 도메인에 수정된 글로벌 예외를 적용한다
  src/main/java/app/bottlenote/global/exception/custom/code/ValidExceptionCode.java
  src/main/java/app/bottlenote/review/dto/request/LocationInfo.java
  src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
  src/main/java/app/bottlenote/review/dto/request/ReviewImageInfo.java
  src/main/java/app/bottlenote/review/dto/request/ReviewModifyRequest.java
  src/main/java/app/bottlenote/support/help/dto/request/HelpRegisterRequest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
Labels: 리펙토링, CI/CD, 배포

#223 feat: need to implement my bottle inquiry function
  docs/index.html
  http/사용자/마이보틀_조회.http
  src/docs/asciidoc/api/follow/follow-search.adoc
  src/docs/asciidoc/api/follow/follow-update.adoc
  src/docs/asciidoc/api/rating/fetch.adoc
  src/docs/asciidoc/api/rating/register.adoc
  src/docs/asciidoc/api/review/likes/update.adoc
  src/docs/asciidoc/api/support/help/help-register.adoc
  src/docs/asciidoc/api/user/user-mybottle.adoc
  src/docs/asciidoc/api/user/user-mypage.adoc
  src/docs/asciidoc/api/user/user-nickname-change.adoc
  src/docs/asciidoc/api/user/user-profile-images-change.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/global/exception/custom/code/ValidExceptionCode.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/like/dto/request/LikesUpdateRequest.java
  src/main/java/app/bottlenote/support/help/dto/request/HelpRegisterRequest.java
  src/main/java/app/bottlenote/user/controller/UserCommandController.java
  src/main/java/app/bottlenote/user/controller/UserQueryController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/domain/UserQueryRepository.java
  src/main/java/app/bottlenote/user/domain/constant/MyBottleSortType.java
  src/main/java/app/bottlenote/user/domain/constant/MyBottleTabType.java
  src/main/java/app/bottlenote/user/dto/dsl/MyBottlePageableCriteria.java
  src/main/java/app/bottlenote/user/dto/request/MyBottleRequest.java
  src/main/java/app/bottlenote/user/dto/request/ProfileImageChangeRequest.java
  src/main/java/app/bottlenote/user/dto/response/MyBottleResponse.java
  src/main/java/app/bottlenote/user/exception/UserExceptionCode.java
  src/main/java/app/bottlenote/user/repository/UserQuerySupporter.java
  src/main/java/app/bottlenote/user/repository/custom/CustomUserRepository.java
  src/main/java/app/bottlenote/user/repository/custom/CustomUserRepositoryImpl.java
  src/main/java/app/bottlenote/user/service/UserQueryService.java
  src/test/java/app/bottlenote/docs/review/RestReviewReplyControllerTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserQueryControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserQueryControllerTest.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
  src/test/java/app/bottlenote/user/fixture/UserQueryFixture.java
  src/test/java/app/bottlenote/user/integration/UserQueryIntegrationTest.java
  src/test/resources/init-script/init-user-mybottle-query.sql
Labels: 문서, 기능, 배포

#231 Hotfix 내가 작성한 리뷰 total count 오류수정
  src/main/java/app/bottlenote/review/repository/ReviewQuerySupporter.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
Labels: 버그, 배포
