Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-06, with the labels that each got.

#114 feat: implement Aggregate Root Repository
  src/main/java/app/bottlenote/alcohols/domain/AlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/repository/AlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/repository/JpaAlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/service/AlcoholQueryService.java
  src/main/java/app/bottlenote/picks/service/PicksCommandService.java
  src/main/java/app/bottlenote/rating/service/RatingCommandService.java
  src/main/java/app/bottlenote/user/domain/UserQueryRepository.java
  src/main/java/app/bottlenote/user/repository/JpaUserQueryRepository.java
  src/main/java/app/bottlenote/user/repository/UserQueryRepository.java
  src/test/java/app/bottlenote/alcohols/fixture/InMemoryAlcoholQueryRepository.java
  src/test/java/app/bottlenote/alcohols/repository/CustomJpaAlcoholQueryRepositoryImplTest.java
  src/test/java/app/bottlenote/alcohols/service/AlcoholQueryServiceTest.java
  src/test/java/app/bottlenote/picks/service/PicksCommandServiceTest.java
  src/test/java/app/bottlenote/rating/fixture/InMemoryRatingRepository.java
  src/test/java/app/bottlenote/rating/service/RatingCommandServiceTest.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
Labels: 데이터, 리펙토링

#117 Pr/93 리뷰등록기능
  database/mysql/init/01-init-table.sql
  docs/tech-spec/review/[Sample]review-registry.md
  docs/tech-spec/review/review-create-techspec.md
  src/docs/asciidoc/api/review/review-create.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/domain/AlcoholsTastingTags.java
  src/main/java/app/bottlenote/alcohols/exception/AlcoholException.java
  src/main/java/app/bottlenote/alcohols/exception/AlcoholExceptionCode.java
  src/main/java/app/bottlenote/alcohols/repository/AlcoholQueryRepository.java
  src/main/java/app/bottlenote/global/ImageUtil.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/history/domain/UserHistory.java
  src/main/java/app/bottlenote/history/domain/constant/UserHistoryAction.java
  src/main/java/app/bottlenote/history/domain/constant/UserHistoryType.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/review/domain/ReviewImage.java
  src/main/java/app/bottlenote/review/domain/ReviewTastingTag.java
  src/main/java/app/bottlenote/review/dto/request/LocationInfo.java
  src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
  src/main/java/app/bottlenote/review/dto/request/ReviewImageInfo.java
  src/main/java/app/bottlenote/review/dto/response/ReviewCreateResponse.java
  src/main/java/app/bottlenote/review/exception/ReviewException.java
  src/main/java/app/bottlenote/review/exception/ReviewExceptionCode.java
  src/main/java/app/bottlenote/review/repository/ReviewImageRepository.java
  src/main/java/app/bottlenote/review/repository/ReviewTastingTagRepository.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/review/controller/ReviewCreateControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/service/ReviewCreateServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewReadServiceTest.java
Labels: 문서, 기능, 리펙토링, 테스트

#113 Pr/110 별점을 등록할 수 있다
  docs/index.html
  http/별점_요청.http
  src/docs/asciidoc/api/alcohols/detail.adoc
  src/docs/asciidoc/api/alcohols/picks.adoc
  src/docs/asciidoc/api/alcohols/popular.adoc
  src/docs/asciidoc/api/alcohols/region.adoc
  src/docs/asciidoc/api/alcohols/search.adoc
  src/docs/asciidoc/api/file/image/upload/presign-url.adoc
  src/docs/asciidoc/api/follow/follow-update.adoc
  src/docs/asciidoc/api/rating/register.adoc
  src/docs/asciidoc/api/restdocs/restdocs-example.adoc
  src/docs/asciidoc/api/review/review-create.adoc
  src/docs/asciidoc/api/review/review-read.adoc
  src/docs/asciidoc/api/support/report/user-report.adoc
  src/docs/asciidoc/api/user/user-login.adoc
  src/docs/asciidoc/api/user/user-nickname-change.adoc
  src/docs/asciidoc/api/user/user-reissue.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/domain/AlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/repository/JpaAlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/service/AlcoholQueryService.java
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/global/service/converter/RatingPointConverter.java
  src/main/java/app/bottlenote/picks/service/PicksCommandService.java
  src/main/java/app/bottlenote/rating/controller/RatingController.java
  src/main/java/app/bottlenote/rating/domain/Rating.java
  src/main/java/app/bottlenote/rating/domain/RatingId.java
  src/main/java/app/bottlenote/rating/domain/RatingPoint.java
  src/main/java/app/bottlenote/rating/domain/RatingRepository.java
  src/main/java/app/bottlenote/rating/dto/request/RatingRegisterRequest.java
  src/main/java/app/bottlenote/rating/dto/response/RatingRegisterResponse.java
  src/main/java/app/bottlenote/rating/exception/RatingExceptionCode.java
  src/main/java/app/bottlenote/rating/repository/JpaRatingRepository.java
  src/main/java/app/bottlenote/rating/repository/RatingRepository.java
  src/main/java/app/bottlenote/rating/service/RatingCommandService.java
  src/main/java/app/bottlenote/rating/service/RatingQueryService.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/main/java/app/bottlenote/user/domain/UserQueryRepository.java
  src/main/java/app/bottlenote/user/repository/JpaUserQueryRepository.java
  src/test/java/app/bottlenote/alcohols/fixture/InMemoryAlcoholQueryRepository.java
  src/test/java/app/bottlenote/alcohols/repository/CustomJpaAlcoholQueryRepositoryImplTest.java
  src/test/java/app/bottlenote/alcohols/service/AlcoholQueryServiceTest.java
  src/test/java/app/bottlenote/docs/rating/RestRatingControllerTest.java
  src/test/java/app/bottlenote/picks/service/PicksCommandServiceTest.java
  src/test/java/app/bottlenote/rating/controller/RatingControllerTest.java
  src/test/java/app/bottlenote/rating/fixture/InMemoryRatingRepository.java
  src/test/java/app/bottlenote/rating/service/RatingCommandServiceTest.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/ReviewCreateServiceTest.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
Labels: 기능

#118 Pr/102 위스키 카테고리 목록들을 제공해준다
  docs/index.html
  http/위스키_조회.http
  src/docs/asciidoc/api/alcohols/categories.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/controller/AlcoholQueryController.java
  src/main/java/app/bottlenote/alcohols/domain/AlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/domain/constant/AlcoholType.java
  src/main/java/app/bottlenote/alcohols/dto/response/CategoryResponse.java
  src/main/java/app/bottlenote/alcohols/repository/JpaAlcoholQueryRepository.java
  src/main/java/app/bottlenote/alcohols/service/AlcoholQueryService.java
  src/main/java/app/bottlenote/global/cache/local/LocalCacheType.java
  src/test/java/app/bottlenote/alcohols/controller/AlcoholQueryControllerTest.java
  src/test/java/app/bottlenote/alcohols/fixture/AlcoholQueryFixture.java
  src/test/java/app/bottlenote/alcohols/fixture/ArgumentsFixture.java
  src/test/java/app/bottlenote/alcohols/fixture/InMemoryAlcoholQueryRepository.java
  src/test/java/app/bottlenote/docs/alcohols/RestAlcoholQueryControllerTest.java
Labels: 문서, 기능

#125 Pr/121 내가 작성한 리뷰 조회
  docs/tech-spec/review/my-review-read-techspec.md
  src/docs/asciidoc/api/overview/global-auth.adoc
  src/docs/asciidoc/api/review/my-review-read.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/common/image/ImageUtil.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/review/repository/CustomReviewRepository.java
  src/main/java/app/bottlenote/review/repository/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/docs/review/ReviewQueryFixture.java
  src/test/java/app/bottlenote/review/controller/MyReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/service/MyReviewReadServiceTest.java
Labels: 기능, 테스트, 배포

#126 Pr/124 토큰 검증 실패시 예외처리 개선
  src/main/java/app/bottlenote/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/app/bottlenote/global/security/jwt/CustomJwtException.java
  src/main/java/app/bottlenote/global/security/jwt/CustomJwtExceptionCode.java
  src/main/java/app/bottlenote/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/app/bottlenote/global/security/jwt/JwtExceptionType.java
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenValidator.java
  src/test/java/app/bottlenote/review/controller/MyReviewReadControllerTest.java
  src/test/java/app/bottlenote/user/controller/OauthControllerTest.java
  src/test/java/app/bottlenote/user/service/JwtTokenValidatorTest.java
Labels: 리펙토링

#119 pr/111 별점 목록 조회 기능
  .gitignore
  docs/index.html
  docs/tech-spec/rating/별점목록조회.md
  docs/wiki/diagram.png
  http/http-client.env.json
  http/별점_목록_조회.http
  src/docs/asciidoc/api/rating/fetch.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/common/profanity/DefaultProfanityClient.java
  src/main/java/app/bottlenote/common/profanity/ProfanityClient.java
  src/main/java/app/bottlenote/rating/controller/RatingController.java
  src/main/java/app/bottlenote/rating/domain/RatingRepository.java
  src/main/java/app/bottlenote/rating/domain/constant/SearchSortType.java
  src/main/java/app/bottlenote/rating/dto/dsl/RatingListFetchCriteria.java
  src/main/java/app/bottlenote/rating/dto/request/RatingListFetchRequest.java
  src/main/java/app/bottlenote/rating/dto/response/RatingListFetchResponse.java
  src/main/java/app/bottlenote/rating/repository/CustomRatingQueryRepository.java
  src/main/java/app/bottlenote/rating/repository/CustomRatingQueryRepositoryImpl.java
  src/main/java/app/bottlenote/rating/repository/JpaRatingRepository.java
  src/main/java/app/bottlenote/rating/repository/RatingQuerySupporter.java
  src/main/java/app/bottlenote/rating/service/RatingQueryService.java
  src/test/java/app/bottlenote/docs/alcohols/RestAlcoholQueryControllerTest.java
  src/test/java/app/bottlenote/docs/rating/RestRatingControllerTest.java
  src/test/java/app/bottlenote/rating/fixture/InMemoryRatingRepository.java
  src/test/java/app/bottlenote/rating/fixture/RatingObjectFixture.java
  src/test/java/app/bottlenote/rating/repository/CustomRatingQueryRepositoryImplTest.java
Labels: 기능, 테스트, 배포

#132 fix: token expire time time 1min
  src/main/java/app/bottlenote/global/security/jwt/JwtTokenProvider.java
Labels: CI/CD, 배포

#139 Hotfix : init-table, init-sql 에 수정된 컬럼 추가
  database/mysql/init/01-init-table.sql
  database/mysql/init/02-init-data.sql
Labels: 데이터

#138 Pr/135 리뷰 삭제 기능
  src/docs/asciidoc/api/review/review-delete.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/alcohols/dto/response/detail/ReviewsDetailInfo.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/review/domain/Review.java
  src/main/java/app/bottlenote/review/domain/constant/ReviewDisplayStatus.java
  src/main/java/app/bottlenote/review/domain/constant/ReviewStatus.java
  src/main/java/app/bottlenote/review/dto/request/ReviewCreateRequest.java
  src/main/java/app/bottlenote/review/dto/request/ReviewModifyRequest.java
  src/main/java/app/bottlenote/review/dto/response/ReviewDetail.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResultMessage.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResultResponse.java
  src/main/java/app/bottlenote/review/dto/vo/ReviewModifyVO.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/main/java/app/bottlenote/review/service/ReviewTastingTagSupport.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/docs/review/ReviewQueryFixture.java
  src/test/java/app/bottlenote/review/controller/MyReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewCreateControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewModifyControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
  src/test/java/app/bottlenote/review/service/MyReviewReadServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewCreateServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewImageSupportTest.java
  src/test/java/app/bottlenote/review/service/ReviewModifyServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewReadServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewTastingTagSupportTest.java
Labels: 문서, 기능, 테스트, 배포

#143 Review 관련 API 리팩토링
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/review/controller/ReviewController.java
  src/main/java/app/bottlenote/review/dto/response/ReviewDetail.java
  src/main/java/app/bottlenote/review/dto/response/ReviewListResponse.java
  src/main/java/app/bottlenote/review/dto/response/ReviewResponse.java
  src/main/java/app/bottlenote/review/repository/ReviewQuerySupporter.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepository.java
  src/main/java/app/bottlenote/review/repository/custom/CustomReviewRepositoryImpl.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/test/java/app/bottlenote/docs/review/ReviewControllerDocsTest.java
  src/test/java/app/bottlenote/review/controller/MyReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/fixture/ReviewObjectFixture.java
  src/test/java/app/bottlenote/review/repository/CustomReviewRepositoryImplTest.java
  src/test/java/app/bottlenote/review/service/MyReviewReadServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewReadServiceTest.java
Labels: 리펙토링, 테스트, 배포

#151 hotfix : 분리되어 있던 리뷰 서비스 레이어 테스트를 하나로 병합
  src/test/java/app/bottlenote/review/service/MyReviewReadServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewCreateServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewDeleteServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewModifyServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewReadServiceTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
Labels: 리펙토링

#154 hotfix : 리뷰 서비스 레이어, 컨트롤러 -> 하나의 클래스로 병합한다.
  src/test/java/app/bottlenote/review/controller/MyReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewCreateControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewDeleteControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewModifyControllerTest.java
  src/test/java/app/bottlenote/review/controller/ReviewReadControllerTest.java
  src/test/java/app/bottlenote/review/service/ReviewServiceTest.java
Labels: 리펙토링
