Repository bottle-note/bottle-note-api-server, pull requests merged in 2024-11, with the labels that each got.

#274 fix : 리뷰 도메인 잘못된 서브쿼리 수정
  src/main/java/app/bottlenote/review/repository/ReviewQuerySupporter.java
  src/test/java/app/bottlenote/review/integration/ReviewSubqueryIntegrationTest.java
Labels: 버그

#272 feat: initializer config about fcm push
  .gitignore
  build.gradle
  database/mysql/init/01-init-table.sql
  docs/index.html
  http/http-client.env.json
  http/사용자 디바이스 토큰/device-token.http
  src/docs/asciidoc/api/external/push/device-token.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/app/bottlenote/BottleNoteApplication.java
  src/main/java/app/bottlenote/global/config/jpa/JpaConfig.java
  src/main/java/app/bottlenote/global/exception/custom/code/ValidExceptionCode.java
  src/main/java/app/external/push/config/FirebaseInitializerConfig.java
  src/main/java/app/external/push/domain/DeviceTokenRepository.java
  src/main/java/app/external/push/domain/Platform.java
  src/main/java/app/external/push/domain/PushStatus.java
  src/main/java/app/external/push/domain/UserDeviceToken.java
  src/main/java/app/external/push/dto/model/TokenMessage.java
  src/main/java/app/external/push/dto/request/TokenSaveRequest.java
  src/main/java/app/external/push/dto/response/TokenSaveResponse.java
  src/main/java/app/external/push/service/DefaultPushHandler.java
  src/main/java/app/external/push/service/PushHandler.java
  src/main/java/app/external/push/service/UserDeviceService.java
  src/main/java/app/external/push/ui/NotificationController.java
  src/test/java/app/external/docs/AbstractRestDocs.java
  src/test/java/app/external/docs/push/ui/NotificationControllerRestDocsTest.java
  src/test/resources/init-script/schema.sql
Labels: 기능, 배포

#284 Pr/262 hot fix 마이보틀 쿼리수정
  http/사용자/마이보틀_조회.http
  src/main/java/app/bottlenote/user/domain/UserQueryRepository.java
  src/main/java/app/bottlenote/user/dto/response/MyBottleResponse.java
  src/main/java/app/bottlenote/user/repository/UserQuerySupporter.java
  src/main/java/app/bottlenote/user/repository/custom/CustomUserRepositoryImpl.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
  src/test/java/app/bottlenote/user/fixture/UserQueryFixture.java
  src/test/java/app/bottlenote/user/integration/UserQueryIntegrationTest.java
Labels: 기능, 리펙토링

#280 feat: added the ability to apply improvements to various problem elements and grant test authorization permissions
  build.gradle
  src/main/java/app/bottlenote/follow/service/FollowService.java
  src/main/java/app/bottlenote/like/service/LikesCommandService.java
  src/main/java/app/bottlenote/picks/service/PicksCommandService.java
  src/main/java/app/bottlenote/rating/service/RatingCommandService.java
  src/main/java/app/bottlenote/rating/service/RatingQueryService.java
  src/main/java/app/bottlenote/review/service/ReviewReplyService.java
  src/main/java/app/bottlenote/review/service/ReviewService.java
  src/main/java/app/bottlenote/support/help/service/HelpService.java
  src/main/java/app/bottlenote/support/report/service/UserReportService.java
  src/main/java/app/bottlenote/user/controller/OauthController.java
  src/main/java/app/bottlenote/user/controller/UserBasicController.java
  src/main/java/app/bottlenote/user/controller/UserMyPageController.java
  src/main/java/app/bottlenote/user/domain/User.java
  src/main/java/app/bottlenote/user/domain/UserRepository.java
  src/main/java/app/bottlenote/user/domain/constant/UserType.java
  src/main/java/app/bottlenote/user/dto/response/TokenDto.java
  src/main/java/app/bottlenote/user/repository/CustomUserRepository.java
  src/main/java/app/bottlenote/user/repository/CustomUserRepositoryImpl.java
  src/main/java/app/bottlenote/user/repository/JpaUserRepository.java
  src/main/java/app/bottlenote/user/repository/OauthRepository.java
  src/main/java/app/bottlenote/user/repository/UserCommandRepository.java
  src/main/java/app/bottlenote/user/service/DefaultUserFacade.java
  src/main/java/app/bottlenote/user/service/NicknameGenerator.java
  src/main/java/app/bottlenote/user/service/OauthService.java
  src/main/java/app/bottlenote/user/service/RandomLetterNicknameGenerator.java
  src/main/java/app/bottlenote/user/service/UserBasicService.java
  src/main/java/app/bottlenote/user/service/UserFacade.java
  src/main/java/app/bottlenote/user/service/UserNotificationService.java
  src/main/java/app/bottlenote/user/service/UserQueryService.java
  src/main/java/app/external/push/service/DefaultPushHandler.java
  src/main/java/app/external/push/service/UserDeviceService.java
  src/test/java/app/bottlenote/DataInitializer.java
  src/test/java/app/bottlenote/IntegrationTestSupport.java
  src/test/java/app/bottlenote/alcohols/repository/CustomJpaAlcoholQueryRepositoryImplTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserChangeContollerTest.java
  src/test/java/app/bottlenote/docs/user/RestDocsUserQueryControllerTest.java
  src/test/java/app/bottlenote/docs/user/RestOauthControllerTest.java
  src/test/java/app/bottlenote/docs/user/RestUserBasicControllerTest.java
  src/test/java/app/bottlenote/follow/service/FollowCommandServiceTest.java
  src/test/java/app/bottlenote/global/config/JpaAuditingIntegrationTest.java
  src/test/java/app/bottlenote/picks/service/PicksCommandServiceTest.java
  src/test/java/app/bottlenote/rating/service/RatingCommandServiceTest.java
  src/test/java/app/bottlenote/review/fixture/FakeUserDomainSupport.java
  src/test/java/app/bottlenote/review/service/ReviewReplyServiceTest.java
  src/test/java/app/bottlenote/support/help/integration/HelpIntegrationTest.java
  src/test/java/app/bottlenote/support/help/service/HelpServiceTest.java
  src/test/java/app/bottlenote/support/report/service/UserReportServiceTest.java
  src/test/java/app/bottlenote/user/controller/OauthControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserBasicControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserNicknameChangeControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserProfileImagesChangeControllerTest.java
  src/test/java/app/bottlenote/user/controller/UserQueryControllerTest.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
  src/test/java/app/bottlenote/user/integration/UserCommandIntegrationTest.java
  src/test/java/app/bottlenote/user/service/JwtTokenValidatorTest.java
  src/test/java/app/bottlenote/user/service/OauthServiceTest.java
  src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
Labels: 기능, 리펙토링

#288 feat: follow 관련 api 리팩토링 및 알콜 조회 시 follow한 유저 정보 노출
  docs/index.html
  src/docs/asciidoc/api/follow/follow-search.adoc
  src/main/java/app/bottlenote/alcohols/dto/response/detail/FriendsDetailInfo.java
  src/main/java/app/bottlenote/common/file/upload/ImageUploadService.java
  src/main/java/app/bottlenote/common/file/upload/dto/response/ImageUploadInfo.java
  src/main/java/app/bottlenote/common/file/upload/dto/response/ImageUploadResponse.java
  src/main/java/app/bottlenote/common/image/ImageUtil.java
  src/main/java/app/bottlenote/common/profanity/DefaultProfanityClient.java
  src/main/java/app/bottlenote/follow/controller/FollowController.java
  src/main/java/app/bottlenote/follow/controller/FollowerController.java
  src/main/java/app/bottlenote/follow/dto/dsl/FollowPageableCriteria.java
  src/main/java/app/bottlenote/follow/dto/response/FollowDetail.java
  src/main/java/app/bottlenote/follow/repository/follow/CustomFollowRepository.java
  src/main/java/app/bottlenote/follow/repository/follow/CustomFollowRepositoryImpl.java
  src/main/java/app/bottlenote/follow/repository/follow/FollowRepository.java
  src/main/java/app/bottlenote/follow/repository/follower/CustomFollowerRepository.java
  src/main/java/app/bottlenote/follow/repository/follower/CustomFollowerRepositoryImpl.java
  src/main/java/app/bottlenote/follow/repository/follower/FollowerRepository.java
  src/main/java/app/bottlenote/follow/service/FollowerService.java
  src/main/java/app/bottlenote/global/security/SecurityConfig.java
  src/main/java/app/bottlenote/user/controller/FollowController.java
  src/main/java/app/bottlenote/user/domain/Follow.java
  src/main/java/app/bottlenote/user/domain/UserRepository.java
  src/main/java/app/bottlenote/user/domain/constant/FollowStatus.java
  src/main/java/app/bottlenote/user/dto/dsl/FollowPageableCriteria.java
  src/main/java/app/bottlenote/user/dto/request/FollowPageableRequest.java
  src/main/java/app/bottlenote/user/dto/request/FollowUpdateRequest.java
  src/main/java/app/bottlenote/user/dto/response/FollowSearchResponse.java
  src/main/java/app/bottlenote/user/dto/response/FollowUpdateResponse.java
  src/main/java/app/bottlenote/user/dto/response/FollowerDetail.java
  src/main/java/app/bottlenote/user/dto/response/FollowingDetail.java
  src/main/java/app/bottlenote/user/dto/response/NicknameChangeResponse.java
  src/main/java/app/bottlenote/user/exception/FollowException.java
  src/main/java/app/bottlenote/user/exception/FollowExceptionCode.java
  src/main/java/app/bottlenote/user/repository/CustomFollowRepository.java
  src/main/java/app/bottlenote/user/repository/CustomFollowRepositoryImpl.java
  src/main/java/app/bottlenote/user/repository/FollowQuerySupporter.java
  src/main/java/app/bottlenote/user/repository/FollowRepository.java
  src/main/java/app/bottlenote/user/repository/FollowerQuerySupporter.java
  src/main/java/app/bottlenote/user/repository/UserQuerySupporter.java
  src/main/java/app/bottlenote/user/service/FollowService.java
  src/test/java/app/bottlenote/common/file/upload/ImageUploadServiceTest.java
  src/test/java/app/bottlenote/config/ModuleConfig.java
  src/test/java/app/bottlenote/docs/alcohols/RestAlcoholQueryControllerTest.java
  src/test/java/app/bottlenote/docs/follow/RestDocsFollowControllerTest.java
  src/test/java/app/bottlenote/docs/follow/RestDocsFollowerControllerTest.java
  src/test/java/app/bottlenote/follow/controller/FollowControllerTest.java
  src/test/java/app/bottlenote/follow/controller/FollowUpdateControllerTest.java
  src/test/java/app/bottlenote/follow/controller/FollowerControllerTest.java
  src/test/java/app/bottlenote/follow/fixture/FollowQueryFixture.java
  src/test/java/app/bottlenote/follow/service/FollowCommandServiceTest.java
  src/test/java/app/bottlenote/user/fixture/InMemoryUserQueryRepository.java
  src/test/java/app/bottlenote/user/service/UserCommandServiceTest.java
Labels: 리펙토링
